language: bash

services:
  - docker

before_script:
  - docker -v
  - docker-compose -v
  - docker-compose build extractor tests
  # Run tests
  - docker-compose run --rm -e GIT_COMMIT_SHA=$TRAVIS_COMMIT -e GIT_BRANCH=$TRAVIS_BRANCH tests
  - sh -c "cd doc && ./run-samples.sh"  

script:
  # Push master image
  - docker pull quay.io/keboola/developer-portal-cli-v2:latest
  - export REPOSITORY=`docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP`
  - docker tag ${KBC_APP_REPOSITORY}:latest ${REPOSITORY}:master
  - eval $(docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP)
  - docker push $REPOSITORY:master
  # Run live test job on new master image
  - docker pull quay.io/keboola/syrup-cli:latest
  - docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job $KBC_DEVELOPERPORTAL_APP $KBC_APP_TEST_CONFIG master

after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true

#notifications:
#  slack:
#    secure: PwqOh1lRxps0xsnaWhxJxotCsazQsSSRyXlcy16CPCq5uVB1hwj8q1nYgK+49mrFtM0q0iQCsUpyu2YeTcuemHdZ8ScyrIPmVpAl20R/O2QcqLUKhzfnGAKe+QW9e4/DkDf9al/4y2OGTg+AXx7e1xajXtHqv0MkqbyI5QsKIMyKwrqg3JH1jtA58IqDg3yXC0+/+rKjYK08ldmt544EkgMsxuF01Lu8RWK6eELlq/7FqQqgVuZla2q2XgDuc1NCiC9eSFfAXua7oUv0rye7/QxGxqRHyLUUfo24gpt9gGEzY1oryBwfuPK1qfrCbFsxtGuMPC0zDfHOHDxuKbPHmId20aRzy4bHtHaHrZeYTQbrRVWU6on0Zo/coe/rjb0aZbSOxMV5V0o3xQ+3K8IxSAh3QM172NT1BW5uKwoL28lZPNSBTbeFMvXLeMvFJCZbqhTe3RC1JxjK3sGD/flUUxg4f2MD46jaEMdJcfc+nGng5bs++cQ42TvEfgijt0Z78Xj+s5kk4vJb/or7ciabSX9NbjFrnd7odw9klRNGvJ4DzmRw8TAyjSMkO6VFzSgxh3CmBTL1rqGBQtM+bZtrVH9GmANLr6oq+yymAJzRHUS0TNipAEKEQ8UjQmFy0ZgnfxKu4dUUhCOEm68Mt+Xtcw/amdq/1Ickvh4iki2H5pg=
#  email: false
