sudo: required
language: bash

services:
  - docker

before_script:
  - docker -v
  - docker-compose -v
  - docker-compose build extractor tests
  # Run tests
  #- docker-compose run --rm -e CC_TEST_REPORTER_ID -e GIT_COMMIT_SHA=$TRAVIS_COMMIT -e GIT_BRANCH=$TRAVIS_BRANCH tests
  - sh -c "cd doc && ./run-samples.sh"
  - export APP_IMAGE=keboola-component
  - docker build . --tag=$APP_IMAGE

after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
