version: '2'

services:
  extractor:
    build: .
    image: keboola/generic-extractor
    volumes:
      - .tmp:/tmp
      - .:/code
      - ./data:/data
    environment:
      - KBC_COMPONENTID=engineroom.ex-generic
      - KBC_PROJECTID=6198
    command:
      - /bin/sh
      - -c
      - "composer install --no-interaction && php /code/run.php --data=/data"
    tty: true
    stdin_open: true

  tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    volumes:
      - ./.git:/code/.git
      - .tmp:/tmp
    command:
      - /code/phpunit.sh
    tty: true
    stdin_open: true

  tests-local:
    build:
      context: .
      dockerfile: Dockerfile-tests
    volumes:
      - .:/code
      - .tmp:/tmp
    command:
      - /bin/sh
      - -c
      - "composer install --no-interaction && /code/phpunit.sh"
    tty: true
    stdin_open: true    